# Simple Docker Compose file for a single PHP app using Nginx
# This example uses PHP 8.4 with Nginx in development mode.
# It mounts the current directory into the container for live development.
# services.app.build.context points to the .docker/v2 directory, where docker can see downwards all the files for building the image.
# services.app.ports: 8080:80 maps port 8080 on the host to port 80 in the container. App runs on port 80 in the container and can be access outside using port 8080.
services:
  app:
    container_name: my-app
    build:
      context: .docker/v2
      dockerfile: php/8.4/nginx/Dockerfile
      args:
        ENABLE_HEALTHCHECK: "true"
    environment:
      ENABLE_HEALTHCHECK: "true"
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck-nginx.sh" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
      # disable: false or just this to disable
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - maninet
# Define the shared network for all services
networks:
  maninet:
    driver: bridge

