services:
  typesense:
    image: typesense/typesense:0.25.1
    restart: unless-stopped
    environment:
      TYPESENSE_API_KEY: "${TYPESENSE_API_KEY}"
    ports: ["${FORWARD_TYPESENSE_PORT:-8108}:8108"]
    command: ["sh","-lc","exec /opt/typesense-server --data-dir=/data --api-key=\"$TYPESENSE_API_KEY\" --listen-port=8108"]
    volumes:
      - typesense_data:/data

volumes:
  typesense_data: {}
