services:
  app:
    container_name: ${APP_SERVICE_NAME:-docky_app}
    build:
      context: ${DOCKER_SUBMODULE_DIR:-.docker/v2}
      dockerfile: php/$DOCKY_REPLACE_PHP_VERSION/$DOCKY_REPLACE_PHP_SERVER/Dockerfile
      target: $DOCKY_REPLACE_PHP_TARGET
      args:
        WWWUSER: "${WWWUSER:-1000}"
        WWWGROUP: "${WWWGROUP:-1000}"
        JS_RUNTIME_REQUIRE_NODE: "true"
        JS_RUNTIME_NODE_VERSION: "22"
        # look for docs for more options to add or disable default extensions and packages
        # you can run bash .docker/v2/docky open-docs to see the documentation of v2.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8081}:80"
      - "${VITE_PORT:-5170}:${VITE_PORT:-5170}"
    environment:
      PUID: ${WWWUSER:-1000}
      PGID: ${WWWGROUP:-1000}
      PHP_IDE_CONFIG: "serverName=docker" # Must match the server name in PHPStorm's server configuration
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      XDEBUG_CLIENT_HOST: "${XDEBUG_CLIENT_HOST:-host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
      SUPERVISOR_PHP_USER: "www-data"
      # EXTRA_APT_PACKAGES: '${EXTRA_APT_PACKAGES:-git jq}'
      # look for docs for more options to setup env vars
    volumes:
      # - custom scripts
      # - ./.scripts/overlays:/opt/overlay:ro
      - ".:/var/www/html"
      - "${DOCKER_SUBMODULE_DIR:-.docker/v2}/common/runtime/configs/php/90-docker-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini"
      - "${DOCKER_SUBMODULE_DIR:-.docker/v2}/common/runtime/configs/php/92-docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./logs/:/var/log"
    # healthcheck:
      # test: ["CMD", "/usr/local/bin/healthcheck-apache.sh"]
      # interval: 30s
      # timeout: 3s
      # retries: 5
    # use depends_on to ensure db is started before app, but does not wait for db to be "ready", only start the docker container
    # depends_on:
    #  - db
    networks:
      - "$DOCKY_REPLACE_NETWORK_NAME"

networks:
  $DOCKY_REPLACE_NETWORK_NAME:
    name: ${DOCKY_REPLACE_NETWORK_NAME:-docky_default}
    driver: bridge

volumes: {}
